### 1. Implement iterative and full recursive version of following sorting techniques and repeat the experiment for larger values of n with different input patterns and plot the comparison graph of number of elements versus execution time taken. The elements can be read from a file or can be generated using random number generator.

-  a) Selection sort

-   b) Insertion sort

-   c) Bubble sort

### 1: Selection Sort:

- a> Iterative Version

In [30]:
import numpy as np
import math

In [31]:
def selection_sort(arr):
    for i in range(0,len(arr)-1):
        curr_minimum_idx = i
        for j in range(i+1,len(arr)):
            if (arr[j] < arr[curr_minimum_idx]):
                curr_minimum_idx = j
        arr[i], arr[curr_minimum_idx] = arr[curr_minimum_idx],arr[i]
    return arr

In [32]:
array = np.array([5,4,3,2,1])
print(selection_sort(array))

[1 2 3 4 5]


- b> Recursive Version

In [33]:
def recursive_selection_sort(arr, n=None, index=0):
    if n is None:
        n = len(arr)
    if index == n:
        return
    min_index = index
    for j in range(index + 1, n):
        if arr[j] < arr[min_index]:
            min_index = j

    arr[index], arr[min_index] = arr[min_index], arr[index]
    recursive_selection_sort(arr, n, index + 1)
    return arr


In [34]:
print(recursive_selection_sort(array))

[1 2 3 4 5]


### 2. Insertion Sort:

- a> Iterative version: 

In [35]:
def insertion_sort(arr):
    for i in range(1,len(arr)):
        j = i
        while( arr[j-1] > arr[j]) and (j>0):
            arr[j-1],arr[j] = arr[j],arr[j-1]
            j -= 1
    return arr 

In [36]:
print(insertion_sort(array))

[1 2 3 4 5]


- b> Recursive Version

In [37]:
def recursive_insertion_sort(arr, n=None):
    if n is None:
        n = len(arr)
    if n <= 1:
        return arr
    recursive_insertion_sort(arr, n - 1)
    last = arr[n - 1]
    j = n - 2
    while j >= 0 and arr[j] > last:
        arr[j + 1] = arr[j]
        j -= 1
        
    arr[j + 1] = last
    return arr


In [38]:
print(recursive_insertion_sort(array))

[1 2 3 4 5]


### 3. Bubble Sort

- a> Iterative Version

In [39]:
def iterative_bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        swapped = False
        # LAST i ELEMENTS ARE ALREADY IN PLACE
        for j in range(0,n-i-1):
            # Swap if the element found is greater than the next element else continue
            if arr[j] > arr[j+1]:
                arr[j],arr[j+1] = arr[j+1],arr[j]
                swapped = True
        if (swapped == False):
            break
    return arr

In [40]:
print(iterative_bubble_sort(array))

[1 2 3 4 5]


- b> Recursive 

In [41]:
def recursive_bubble_sort(arr,n):
    if n ==1:
        return
    for i in range(n-1):
        if arr[i] > arr[i+1]:
            arr[i],arr[i+1] = arr[i+1],arr[i]
    recursive_bubble_sort(arr,n-1)

In [42]:
recursive_bubble_sort(array,len(array))
print(array)
array = np.array([5,4,3,2,1]) #Need tp revert array back to the original so as to use it in next sorting techniques

[1 2 3 4 5]


### 2. Given an array of integers nums, sort the array in ascending order and return it. You must solve the problem without using any built-in functions in O(nlog(n)) time complexity and with the smallest space complexity possible.

Sorting functions with O(nlog(n)) complexity are merge sort and quick sort (I am going to implement Quick Sort)

In [43]:
#function that considers last elements as pivot
def partition(a,start,end):
    i = start-1
    pivot = a[end] #pivot element
    for j in range(start,end):
        if(a[j]<=pivot):
            i = i+1
            a[i],a[j] = a[j],a[i]
    a[i+1],a[end] = a[end],a[i+1]
    return i+1


#function to implement quick sort
def quick(a,start,end):
    if (start<end):
        p = partition(a,start,end)
        quick(a,start,p-1)
        quick(a,p+1,end)


def printArr(a):
    for i in range(len(a)):
        print(a[i],end=" ")



In [44]:
print("Before")
printArr(array)
print("\nAfter")
quick(array,0,len(array)-1)
printArr(array)

Before
5 4 3 2 1 
After
1 2 3 4 5 

- Selection sort: O(n^2) in all cases
- Insertion sort: O(n) = best case, O(n^2) in average/worst cases
- Bubble Sort: O(n) = best case, O(n^2) in average/worst cases
- Quick Sort: O(nlog(n)) = Best Casse, O(n^2) in worst case.